.PHONY: all clean

all:
	$(MAKE) -C day1
	$(MAKE) -C day2
	$(MAKE) -C day3
	$(MAKE) -C day4
	$(MAKE) -C day5

clean:
	$(MAKE) -C day1 clean
	$(MAKE) -C day2 clean
	$(MAKE) -C day3 clean
	$(MAKE) -C day4 clean
	$(MAKE) -C day5 clean



